{
    "OpenVPN/openvpn": [
        {
            "cve_name": "CVE-2020-11810",
            "patch_url": "https://github.com/OpenVPN/openvpn/commit/37bc691e7d26ea4eb61a8a434ebd7a9ae76225ab.patch",
            "reaching_path": "https://security-tracker.debian.org/tracker/CVE-2020-11810",
            "repository_url": "OpenVPN/openvpn",
            "owner": "OpenVPN",
            "repo": "openvpn",
            "base_hash": "3b06b57d9f1d972ec16f0893d06697439c1bb1fe",
            "head_hash": "37bc691e7d26ea4eb61a8a434ebd7a9ae76225ab",
            "function_names": [
                "multi_process_incoming_link"
            ],
            "affected_version":[
                "2.4.0 to 2.4.8"
            ],
            "binary_version":[
                "2.4.0"
            ],
            "old_files": [
                {
                    "filename": "src/openvpn/multi.c",
                    "lines": [
                        2580
                    ]
                }
            ],
            "new_files": [
                {
                    "filename": "src/openvpn/multi.c",
                    "lines": [
                        2580,
                        2581
                    ]
                }
            ]
        }
    ]
}